// Rust: Load proven constants from model
// No hardcoded magic numbers - all from Lean4/MiniZinc

use serde::{Deserialize, Serialize};
use std::fs;

#[derive(Debug, Deserialize, Serialize)]
pub struct MonsterModel {
    pub monster_primes: Vec<u64>,
    pub num_shards: usize,
    pub emoji_cube_size: usize,
    pub compressed_size: usize,
    pub compression_ratio: usize,
    pub performance: PerformanceModel,
    pub coordinates: CoordinateModel,
}

#[derive(Debug, Deserialize, Serialize)]
pub struct PerformanceModel {
    pub malloc_max: f64,
    pub throughput_min: usize,
    pub latency_max: usize,
}

#[derive(Debug, Deserialize, Serialize)]
pub struct CoordinateModel {
    pub lat_min: f64,
    pub lat_max: f64,
    pub lon_min: f64,
    pub lon_max: f64,
}

impl MonsterModel {
    /// Load proven model from JSON (generated by Lean4)
    pub fn load() -> Result<Self, Box<dyn std::error::Error>> {
        let json = fs::read_to_string("proofs/model.json")?;
        let model: MonsterModel = serde_json::from_str(&json)?;
        
        // Validate loaded model
        model.validate()?;
        
        Ok(model)
    }
    
    /// Validate all invariants (proven in Lean4)
    fn validate(&self) -> Result<(), String> {
        // Invariant: 71 is largest Monster prime
        if self.num_shards != 71 {
            return Err(format!("Invalid num_shards: {}", self.num_shards));
        }
        
        // Invariant: Emoji cube is 24³
        if self.emoji_cube_size != 24 * 24 * 24 {
            return Err(format!("Invalid cube size: {}", self.emoji_cube_size));
        }
        
        // Invariant: Compression ratio
        let ratio = self.emoji_cube_size / self.compressed_size;
        if ratio != self.compression_ratio {
            return Err(format!("Invalid compression ratio: {}", ratio));
        }
        
        // Invariant: Coordinates in valid range
        if self.coordinates.lat_min != -90.0 || self.coordinates.lat_max != 90.0 {
            return Err("Invalid latitude bounds".to_string());
        }
        
        if self.coordinates.lon_min != -180.0 || self.coordinates.lon_max != 180.0 {
            return Err("Invalid longitude bounds".to_string());
        }
        
        Ok(())
    }
    
    /// Get shard count (proven to be 71)
    pub fn num_shards(&self) -> usize {
        self.num_shards
    }
    
    /// Get Monster primes (proven list)
    pub fn monster_primes(&self) -> &[u64] {
        &self.monster_primes
    }
    
    /// Validate coordinates against proven bounds
    pub fn validate_coordinates(&self, lat: f64, lon: f64) -> Result<(), String> {
        if lat < self.coordinates.lat_min || lat > self.coordinates.lat_max {
            return Err(format!("Latitude {} out of bounds", lat));
        }
        
        if lon < self.coordinates.lon_min || lon > self.coordinates.lon_max {
            return Err(format!("Longitude {} out of bounds", lon));
        }
        
        Ok(())
    }
    
    /// Check if performance meets proven targets
    pub fn validate_performance(
        &self,
        malloc_percent: f64,
        throughput: usize,
        latency_ms: usize,
    ) -> Result<(), String> {
        if malloc_percent >= self.performance.malloc_max {
            return Err(format!("Malloc {}% exceeds max {}%", 
                malloc_percent, self.performance.malloc_max));
        }
        
        if throughput < self.performance.throughput_min {
            return Err(format!("Throughput {} < min {}", 
                throughput, self.performance.throughput_min));
        }
        
        if latency_ms >= self.performance.latency_max {
            return Err(format!("Latency {}ms exceeds max {}ms", 
                latency_ms, self.performance.latency_max));
        }
        
        Ok(())
    }
}

// Global model instance (loaded once at startup)
lazy_static::lazy_static! {
    pub static ref MODEL: MonsterModel = MonsterModel::load()
        .expect("Failed to load proven model");
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_model_loads() {
        let model = MonsterModel::load();
        assert!(model.is_ok());
    }

    #[test]
    fn test_invariants_validated() {
        let model = MODEL.clone();
        assert_eq!(model.num_shards(), 71);
        assert_eq!(model.emoji_cube_size, 13824);
        assert_eq!(model.compressed_size, 150);
    }

    #[test]
    fn test_coordinate_validation() {
        let model = &*MODEL;
        
        // Valid coordinates
        assert!(model.validate_coordinates(10.9617, 79.3881).is_ok());
        
        // Invalid latitude
        assert!(model.validate_coordinates(91.0, 0.0).is_err());
        
        // Invalid longitude
        assert!(model.validate_coordinates(0.0, 181.0).is_err());
    }

    #[test]
    fn test_performance_validation() {
        let model = &*MODEL;
        
        // Valid performance
        assert!(model.validate_performance(0.17, 1000, 50).is_ok());
        
        // Invalid malloc
        assert!(model.validate_performance(1.5, 1000, 50).is_err());
        
        // Invalid throughput
        assert!(model.validate_performance(0.17, 500, 50).is_err());
        
        // Invalid latency
        assert!(model.validate_performance(0.17, 1000, 150).is_err());
    }
}
